global:
    elements:
      login:
          - "#login"
          - ".login"
          - "button .login"
      username_input: "#username"


    pages:
      home: "https://google.com"
      login: "login"

    base_url: "http://etoole.test"

