configuration:
  timeout: 60s
  slowMotion: 2s
  parallel: 4
  gherkin_location: "./features"  # Chemin vers les fichiers Gherkin
  tags: "@AA && ~@QHQ"




application:
  app_name: "MonApplication"
  app_description: "ma chic app"
  app_version: "1.0.0"

reporting:
  enable: true
  report_format: "html"  # Options possibles : "html", "json", "xml"

